import { Encode_Sans } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

const encode_sans = Encode_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Tann Trim",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={encode_sans.className} style={{background:"black"}}>
       {/* <header><Header/></header>  */}
        {children}</body>
    </html>
  );
}
